# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  math-engine:    katex

# Permalinks
permalink:        pretty

# Setup
title:            Mathstache
description:      'A math blog by Miguel Serrano.'
url:

author:
  name:           'Miguel Serrano'

paginate:         5

excerpt_separator: <!-- excerpt-end -->

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown-math-katex

# Custom vars
version:          1.0

github:           https://github.com/homomorfismo
