# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mathstache
description:      'A math blog by Miguel Serrano.'
url:              https://homomorfismo.github.io
baseurl:          https://homomorfismo.github.io/

author:
  name:           'Miguel Serrano'

paginate:         5

# Custom vars
version:          1.0

github:           https://github.com/homomorfismo
