# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mathstache
description:      'A math blog by Miguel Serrano.'
url:              https://mathstache.com
baseurl:          https://homomorfismo.github.io/

author:
  name:           'Miguel Serrano'

paginate:         5

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-katex

# Custom vars
version:          1.0

github:           https://github.com/homomorfismo
